version: 2.1
orbs:
  owasp: entur/owasp@0.0.10
executors:
  default:
    working_directory: ~/mattermost-redux
    docker:
      - image: circleci/node:11.3.0

aliases:
  - &restore_cache
    restore_cache:
      key: dependencies-{{ checksum "package-lock.json" }}
  - &save_cache
    save_cache:
      key: dependencies-{{ checksum "package-lock.json" }}
      paths:
        - node_modules

jobs:
  install:
    executor:
      name: default
    steps:
      - checkout
      - run: ls -la
      - *restore_cache
      - run: npm ci
      - run: ls -la
      - *save_cache

  check-deps:
    parameters:
      cve_data_directory:
        type: string
        default: "~/.owasp/dependency-check-data"
    working_directory: ~/mattermost-redux
    executor: owasp/default
    environment:
      version_url: "https://jeremylong.github.io/DependencyCheck/current.txt"
      executable_url: "https://dl.bintray.com/jeremy-long/owasp/dependency-check-VERSION-release.zip"
    steps:
      - checkout
      - *restore_cache
      - run:
          name: Checkout config
          command: cd .. && git clone https://github.com/mattermost/security-automation-config
      - run:
          name: Install Go
          command: sudo apt-get update && sudo apt-get install golang
      - owasp/with_commandline:
          steps:
            # Taken from https://github.com/entur/owasp-orb/blob/master/src/%40orb.yml#L349-L361
            - owasp/generate_cache_keys:
                cache_key: commmandline-default-cache-key-v6
            - owasp/restore_owasp_cache
            - run:
                name: Update OWASP Dependency-Check Database
                command: ~/.owasp/dependency-check/bin/dependency-check.sh --data << parameters.cve_data_directory >> --updateonly
            - owasp/store_owasp_cache:
                cve_data_directory: <<parameters.cve_data_directory>>
            - run:
                name: Run OWASP Dependency-Check Analyzer
                command: |
                  ~/.owasp/dependency-check/bin/dependency-check.sh \
                    --data << parameters.cve_data_directory >> --format ALL --noupdate --enableExperimental \
                    --propertyfile ../security-automation-config/dependency-check/dependencycheck.properties \
                    --suppression ../security-automation-config/dependency-check/suppression.xml \
                    --suppression ../security-automation-config/dependency-check/suppression.$CIRCLE_PROJECT_REPONAME.xml \
                    --scan './**/*' || true
            - owasp/collect_reports:
                persist_to_workspace: false
      - run:
          name: Post results to Mattermost
          command: go run ../security-automation-config/dependency-check/post_results.go

  lint:
    executor:
      name: default
    steps:
      - checkout
      - *restore_cache
      - run: npm run check
      - run: npm run tsc

  test:
    executor:
      name: default
    steps:
      - checkout
      - *restore_cache
      - run: npm test
      - store_test_results:
          path: build/

workflows:
  version: 2
  pr-build:
    jobs:
      - install
      - check-deps:
          context: sast-webhook
          requires:
            - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - lint
